import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

class ReportService {
  // دالة لتوليد الـ PDF وحفظه
  static Future<File> generateMaterialReport({
    required String concrete,
    required String steel,
    String? city,
    String? weatherAdvice,
    String? companyName,
  }) async {
    final prefs = await SharedPreferences.getInstance();
    final companyName = prefs.getString('company_name') ?? 'BENAA PRO';
    final pdf = pw.Document();

    // ملاحظة: استخدمنا اللغة الإنجليزية في التقرير لأن اللغة العربية في الـ PDF
    // تتطلب دمج ملف خط (TTF). واللغة الإنجليزية هي الشائعة لطلبات المواد (Material Request) في الإمارات.
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Container(
            padding: const pw.EdgeInsets.all(20),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                // الترويسة (Header)
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      companyName ?? "BENAA PRO",
                      style: pw.TextStyle(
                        fontSize: 24,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.blue900,
                      ),
                    ),
                    pw.Text(
                      "MATERIAL REQUEST",
                      style: pw.TextStyle(
                        fontSize: 18,
                        color: PdfColors.grey700,
                      ),
                    ),
                  ],
                ),
                pw.Divider(thickness: 2),
                pw.SizedBox(height: 20),

                // تاريخ التقرير
                pw.Text(
                  "Date: ${DateTime.now().toString().split(' ')[0]}",
                  style: const pw.TextStyle(fontSize: 14),
                ),
                pw.SizedBox(height: 30),

                // جدول الكميات الممحسوبة
                pw.Text(
                  "1. Required Quantities:",
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 10),
                pw.Container(
                  padding: const pw.EdgeInsets.all(10),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey),
                  ),
                  child: pw.Column(
                    children: [
                      pw.Row(
                        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                        children: [
                          pw.Text("Ready-Mix Concrete:"),
                          pw.Text(
                            "$concrete m3",
                            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                          ),
                        ],
                      ),
                      pw.SizedBox(height: 5),
                      pw.Row(
                        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                        children: [
                          pw.Text("Steel Rebar:"),
                          pw.Text(
                            "$steel Tons",
                            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),

                pw.SizedBox(height: 30),

                // توصيات الطقس (إذا قام المهندس بفحصها)
                if (city != null && weatherAdvice != null) ...[
                  pw.Text(
                    "2. Site Advisor ($city):",
                    style: pw.TextStyle(
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 10),
                  pw.Text(
                    weatherAdvice,
                    style: const pw.TextStyle(
                      fontSize: 14,
                      color: PdfColors.red800,
                    ),
                  ),
                ],

                pw.Spacer(),
                // التوقيع
                pw.Divider(),
                pw.Text(
                  "Generated by Benaa Pro App - UAE Site Master",
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey,
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );

    // حفظ الملف في المسار المؤقت للهاتف
    final output = await getTemporaryDirectory();
    final file = File(
      "${output.path}/Material_Request_${DateTime.now().millisecondsSinceEpoch}.pdf",
    );
    await file.writeAsBytes(await pdf.save());

    return file;
  }
}
